name: home
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: 3.5.0
  flutter: 3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  gap: ^3.0.1
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
