name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  core_assets: ^0.0.1
  core_design: ^0.0.1
  core_navigation: ^0.0.1
  core_utils: ^0.0.1
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
