name: home
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  awesome_extensions: ^2.0.19
  core_assets: ^0.0.1
  core_utils: ^0.0.1
  core_widgets: ^0.0.1
  flutter:
    sdk: flutter
  go_router: ^14.2.3
  google_fonts: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
