include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - always_put_required_named_parameters_first
    - prefer_relative_imports
    - sort_pub_dependencies
    - prefer_spread_collections
    - super_goes_last
    - lines_longer_than_80_chars

analyzer:
  exclude:
    - "**/*.g.dart" # Exclude generated files if needed
