name: bank_shots_workspace
repository: https://github.com/sugith10/bank-shots

packages:
  - apps/*
  - core/*
  - features/*
  - services/*

command:
  bootstrap:
    environment:
      sdk: 3.5.0
      flutter: 3.24.0

    dependencies:
      core_utils: ^0.0.1
      core_widgets: ^0.0.1
      core_assets: ^0.0.1
      goal: ^0.0.1
      home: ^0.0.1
      flutter_riverpod: ^2.5.3
      go_router: ^14.2.3
      intl: ^0.19.0

  dev_dependencies:
    build_runner: ^2.4.12

  usePubspecOverrides: true

scripts:
  analyze:
    run: melos exec -- flutter analyze

  format:
    run: melos exec -- flutter format .

  g:
    description: Build all generated files for all packages.
    run: find . \( -name '*.g.dart' -o -name '*.freezed.dart' -o -name '*.gen.dart' \) -type f -delete; dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 3
      failFast: true
      orderDependents: true
    packageFilters:
      dependsOn: "build_runner"
