name: bank_shots_workspace
description: Bank Shots workspace

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  gap: ^3.0.1
  go_router: ^14.2.3

dev_dependencies:
  melos: ^6.1.0
