name: bank_shots
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  awesome_extensions: ^2.0.18
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  gap: ^3.0.1
  go_router: ^14.3.0
  iconly: ^1.0.1
  intl: ^0.19.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/outfit/Outfit-Black.ttf
          weight: 900

flutter_gen:
  integrations:
    flutter_svg: true
  output: lib/core/gen/
