name: bank_shots_workspace
description: Bank Shots workspace

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.14
  melos: ^6.2.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
