name: goal
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  animate_do: ^3.3.4
  awesome_extensions: ^2.0.18
  core_utils: ^0.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  liquid_swipe: ^3.1.0
  flutter_riverpod: ^2.5.3
  gap: ^3.0.1
  go_router: ^14.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
