name: goal
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  animate_do: ^3.3.4
  core_assets: ^0.0.1
  core_navigation: ^0.0.1
  core_provider: ^0.0.1
  core_utils: ^0.0.1
  core_widgets: ^0.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.16
  liquid_swipe: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
