name: core_utils
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter packages.
flutter:
  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/outfit/Outfit-Black.ttf
          weight: 900

flutter_gen:
  integrations:
  output: gen/
