name: core_utils
description: "Core utility package for the project."
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  flutter:
    sdk: flutter
  iconly: ^1.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
