name: core_navigation
description: "Core navigation package"
version: 0.0.1
publish_to: none

environment:
  sdk: 3.5.0

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
