name: core_design
description: "Core widget package"
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  core_assets: ^0.0.1
  core_utils: ^0.0.1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  iconly: ^1.0.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
