name: core_assets
description: "A new Flutter package project."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  # The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/png/
    - assets/svg/
    - assets/webp/

  fonts:
    - family: outfit
      fonts:
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
        - asset: assets/fonts/outfit/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/outfit/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/outfit/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/outfit/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/outfit/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/outfit/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/outfit/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/outfit/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/outfit/Outfit-Black.ttf
          weight: 900
    - family: be_vietnam_pro
      fonts:
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Regular.ttf
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Thin.ttf
          weight: 100
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Light.ttf
          weight: 300
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Regular.ttf
          weight: 400
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Medium.ttf
          weight: 500
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/be_vietnam_pro/BeVietnamPro-Black.ttf
          weight: 900

flutter_gen:
  integrations:
  output: lib/gen/

  assets:
    outputs:
      package_parameter_enabled: true

  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: AssetColors
