name: bank_shots
description: "Financial goal setting and tracking application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  core_navigation: ^0.0.1
  core_provider: ^0.0.1
  core_utils: ^0.0.1
  core_design: ^0.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10
  goal: ^0.0.1
  home: ^0.0.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true

  # assets:
  # - assets/png/
  # - assets/svg/
  # - assets/webp/
