name: bank_shots
description: "Financial goal setting and tracking application."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 3.5.0

dependencies:
  animate_do: ^3.3.4
  awesome_extensions: ^2.0.18
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.3
  flutter_svg: ^2.0.10
  gap: ^3.0.1
  go_router: ^14.2.3
  google_fonts: ^6.2.1
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0
  intl: ^0.19.0
  liquid_swipe: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.7.1
  hive_ce_generator: ^1.7.0

flutter:
  uses-material-design: true

  # assets:
  # - assets/png/
  # - assets/svg/
  # - assets/webp/
